// flow-typed signature: 72744c21d09f0f6676ad4455cffc0156
// flow-typed version: <<STUB>>/babel-plugin-react-intl-auto_v^1.7.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-intl-auto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-intl-auto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-intl-auto/lib/__tests__/components.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl-auto/lib/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl-auto/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl-auto/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-intl-auto/lib/__tests__/components.test.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl-auto/lib/__tests__/components.test'>;
}
declare module 'babel-plugin-react-intl-auto/lib/__tests__/index.test.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl-auto/lib/__tests__/index.test'>;
}
declare module 'babel-plugin-react-intl-auto/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl-auto/lib/index'>;
}
declare module 'babel-plugin-react-intl-auto/lib/types.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl-auto/lib/types'>;
}
