// flow-typed signature: bb1452ba02643eed47f990032237e5fb
// flow-typed version: <<STUB>>/babel-tap_v^5.0.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-tap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-tap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-tap/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-tap/cli.js' {
  declare module.exports: $Exports<'babel-tap/cli'>;
}
declare module 'babel-tap/index' {
  declare module.exports: $Exports<'babel-tap'>;
}
declare module 'babel-tap/index.js' {
  declare module.exports: $Exports<'babel-tap'>;
}
