// flow-typed signature: 5bec7facd4614f65f99634409b7d1fd4
// flow-typed version: <<STUB>>/bcp-47_v^1.0.5/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bcp-47'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bcp-47' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bcp-47/lib/parse' {
  declare module.exports: any;
}

declare module 'bcp-47/lib/stringify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bcp-47/index' {
  declare module.exports: $Exports<'bcp-47'>;
}
declare module 'bcp-47/index.js' {
  declare module.exports: $Exports<'bcp-47'>;
}
declare module 'bcp-47/lib/parse.js' {
  declare module.exports: $Exports<'bcp-47/lib/parse'>;
}
declare module 'bcp-47/lib/stringify.js' {
  declare module.exports: $Exports<'bcp-47/lib/stringify'>;
}
