// flow-typed signature: e6cd16fd334458c8d4d2b39c78a01196
// flow-typed version: <<STUB>>/dependency-check_v^3.3.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dependency-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dependency-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dependency-check/cli' {
  declare module.exports: any;
}

declare module 'dependency-check/test/donkey/index' {
  declare module.exports: any;
}

declare module 'dependency-check/test/foo' {
  declare module.exports: any;
}

declare module 'dependency-check/test/index' {
  declare module.exports: any;
}

declare module 'dependency-check/test/pizza' {
  declare module.exports: any;
}

declare module 'dependency-check/test/scoped' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dependency-check/cli.js' {
  declare module.exports: $Exports<'dependency-check/cli'>;
}
declare module 'dependency-check/index' {
  declare module.exports: $Exports<'dependency-check'>;
}
declare module 'dependency-check/index.js' {
  declare module.exports: $Exports<'dependency-check'>;
}
declare module 'dependency-check/test/donkey/index.js' {
  declare module.exports: $Exports<'dependency-check/test/donkey/index'>;
}
declare module 'dependency-check/test/foo.js' {
  declare module.exports: $Exports<'dependency-check/test/foo'>;
}
declare module 'dependency-check/test/index.js' {
  declare module.exports: $Exports<'dependency-check/test/index'>;
}
declare module 'dependency-check/test/pizza.js' {
  declare module.exports: $Exports<'dependency-check/test/pizza'>;
}
declare module 'dependency-check/test/scoped.js' {
  declare module.exports: $Exports<'dependency-check/test/scoped'>;
}
