// flow-typed signature: cc05c01a7ad9c8e5ab7c9af2f0c5552a
// flow-typed version: <<STUB>>/dot-prop_v^5.1.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dot-prop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dot-prop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'dot-prop/index' {
  declare module.exports: $Exports<'dot-prop'>;
}
declare module 'dot-prop/index.js' {
  declare module.exports: $Exports<'dot-prop'>;
}
