// flow-typed signature: 3799a1e1c7409c6c223fba71e3a38cbf
// flow-typed version: <<STUB>>/dot-prop-immutable_v^1.5.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dot-prop-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dot-prop-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'dot-prop-immutable/index' {
  declare module.exports: $Exports<'dot-prop-immutable'>;
}
declare module 'dot-prop-immutable/index.js' {
  declare module.exports: $Exports<'dot-prop-immutable'>;
}
