// flow-typed signature: 6ca4b9fe3ee3a813c2a85c288f055246
// flow-typed version: <<STUB>>/extract-react-intl-messages_v^1.0.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-react-intl-messages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-react-intl-messages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-react-intl-messages/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-react-intl-messages/cli.js' {
  declare module.exports: $Exports<'extract-react-intl-messages/cli'>;
}
declare module 'extract-react-intl-messages/index' {
  declare module.exports: $Exports<'extract-react-intl-messages'>;
}
declare module 'extract-react-intl-messages/index.js' {
  declare module.exports: $Exports<'extract-react-intl-messages'>;
}
