// flow-typed signature: 6f8a856e821074a94d76ec0f92d1345d
// flow-typed version: <<STUB>>/feature-filter-geojson_v^1.0.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feature-filter-geojson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feature-filter-geojson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feature-filter-geojson/bench/bench' {
  declare module.exports: any;
}

declare module 'feature-filter-geojson/bench/big' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feature-filter-geojson/bench/bench.js' {
  declare module.exports: $Exports<'feature-filter-geojson/bench/bench'>;
}
declare module 'feature-filter-geojson/bench/big.js' {
  declare module.exports: $Exports<'feature-filter-geojson/bench/big'>;
}
declare module 'feature-filter-geojson/index' {
  declare module.exports: $Exports<'feature-filter-geojson'>;
}
declare module 'feature-filter-geojson/index.js' {
  declare module.exports: $Exports<'feature-filter-geojson'>;
}
