// flow-typed signature: df682d2518ad22f2b7e8ce444b5ed58d
// flow-typed version: <<STUB>>/is-buffer_v^2.0.3/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-buffer/index' {
  declare module.exports: $Exports<'is-buffer'>;
}
declare module 'is-buffer/index.js' {
  declare module.exports: $Exports<'is-buffer'>;
}
