// flow-typed signature: 6fd1ad63928574f217444eabd7e9c21d
// flow-typed version: <<STUB>>/is-equal-shallow_v^0.1.3/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-equal-shallow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-equal-shallow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-equal-shallow/index' {
  declare module.exports: $Exports<'is-equal-shallow'>;
}
declare module 'is-equal-shallow/index.js' {
  declare module.exports: $Exports<'is-equal-shallow'>;
}
