// flow-typed signature: 7bf27d26127df5adca22616d7b4c2b7f
// flow-typed version: <<STUB>>/isobject_v^4.0.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isobject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isobject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isobject/index.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isobject/index.cjs.js' {
  declare module.exports: $Exports<'isobject/index.cjs'>;
}
declare module 'isobject/index' {
  declare module.exports: $Exports<'isobject'>;
}
declare module 'isobject/index.js' {
  declare module.exports: $Exports<'isobject'>;
}
