// flow-typed signature: a4a19a377d9ab6eaf8688fc9970ede5b
// flow-typed version: <<STUB>>/mapbox-gl_v^0.47.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapbox-gl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapbox-gl/build/generate-access-token-script' {
  declare module.exports: any;
}

declare module 'mapbox-gl/build/generate-flow-typed-style-spec' {
  declare module.exports: any;
}

declare module 'mapbox-gl/build/generate-struct-arrays' {
  declare module.exports: any;
}

declare module 'mapbox-gl/build/generate-style-code' {
  declare module.exports: any;
}

declare module 'mapbox-gl/build/minifyify_style_spec' {
  declare module.exports: any;
}

declare module 'mapbox-gl/build/rollup_plugin_minify_style_spec' {
  declare module.exports: any;
}

declare module 'mapbox-gl/build/rollup_plugins' {
  declare module.exports: any;
}

declare module 'mapbox-gl/build/strictify' {
  declare module.exports: any;
}

declare module 'mapbox-gl/dist/mapbox-gl-dev' {
  declare module.exports: any;
}

declare module 'mapbox-gl/dist/mapbox-gl' {
  declare module.exports: any;
}

declare module 'mapbox-gl/dist/style-spec/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/geojson' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/mapbox-gl-js-test' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/mapbox-gl-supported' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/mapbox-unitbezier' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/pbf' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/point-geometry' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/pointlike' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/shelf-pack' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/style-spec' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/unitbezier' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/vector-tile' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-typed/window' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/array_types' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/circle_attributes' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/circle_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/fill_attributes' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/fill_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/fill_extrusion_attributes' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/fill_extrusion_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/heatmap_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/line_attributes' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/line_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/symbol_attributes' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/symbol_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/dem_data' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/extent' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/feature_index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/index_array_type' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/load_geometry' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/pos_attributes' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/program_configuration' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/raster_bounds_attributes' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/segment' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/coordinate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/lng_lat_bounds' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/lng_lat' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/transform' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/gl/color_mode' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/gl/context' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/gl/depth_mode' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/gl/framebuffer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/gl/index_buffer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/gl/stencil_mode' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/gl/types' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/gl/value' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/gl/vertex_buffer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_background' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_circle' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_collision_debug' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_debug' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_fill_extrusion' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_fill' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_heatmap' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_hillshade' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_line' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_raster' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_symbol' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/glyph_atlas' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/glyph_manager' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/image_atlas' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/image_manager' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/line_atlas' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/painter' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/pattern' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/program' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/texture' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/tile_mask' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/vertex_array_object' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/shaders/encode_attribute' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/shaders/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/canvas_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/geojson_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/geojson_worker_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/geojson_wrapper' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/image_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/load_tilejson' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/pixels_to_tile_units' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/query_features' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/raster_dem_tile_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/raster_dem_tile_worker_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/raster_tile_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/rtl_text_plugin' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/source_cache' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/source_state' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/tile_bounds' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/tile_cache' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/tile_id' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/tile' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/vector_tile_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/vector_tile_worker_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/video_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/worker_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/worker_tile' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/worker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/build/strictify' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/composite' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/declass' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/deref' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/diff' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/dist/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/error/parsing_error' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/error/validation_error' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/compound_expression' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/array' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/assertion' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/at' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/case' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/coalesce' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/coercion' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/collator' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/equals' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/interpolate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/length' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/let' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/literal' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/match' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/step' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/definitions/var' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/evaluation_context' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/expression' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/is_constant' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/parsing_context' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/parsing_error' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/runtime_error' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/scope' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/stops' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/types' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/expression/values' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/feature_filter/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/format' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/function/convert' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/function/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/group_by_layout' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/migrate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/migrate/v8' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/migrate/v9' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/reference/latest' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/rollup.config' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/style-spec' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/color_spaces' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/color' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/deep_equal' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/eval_support' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/extend' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/get_type' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/interpolate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/ref_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/result' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/unbundle_jsonlint' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate_style' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate_style.min' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/latest' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_array' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_boolean' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_color' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_constants' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_enum' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_expression' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_filter' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_function' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_glyphs_url' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_layout_property' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_light' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_number' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_object' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_paint_property' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_property' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_string' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/create_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/cross_faded' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/evaluation_parameters' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/light' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/load_glyph_range' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/load_sprite' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/parse_glyph_pbf' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/pauseable_placement' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/query_utils' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_glyph' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_image' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer_index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/background_style_layer_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/background_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/circle_style_layer_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/circle_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/fill_style_layer_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/fill_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/heatmap_style_layer_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/heatmap_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/hillshade_style_layer_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/hillshade_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/line_style_layer_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/line_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/raster_style_layer_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/raster_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/symbol_style_layer_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/symbol_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/typed_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/validate_style' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/zoom_history' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/anchor' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/check_max_angle' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/clip_line' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/collision_feature' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/collision_index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/cross_tile_symbol_index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/get_anchors' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/grid_index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/mergelines' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/opacity_state' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/placement' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/projection' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/quads' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/shaping' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/symbol_layout' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/symbol_size' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/transform_text' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/types/callback' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/types/cancelable' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/types/performance_resource_timing' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/types/tilejson' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/types/transferable' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/anchor' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/bind_handlers' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/camera' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/attribution_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/fullscreen_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/geolocate_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/logo_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/navigation_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/scale_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/events' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/box_zoom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/dblclick_zoom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/drag_pan' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/drag_rotate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/keyboard' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/scroll_zoom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/touch_zoom_rotate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/hash' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/map' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/marker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/popup' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/actor' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/ajax' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/browser' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/browser/web_worker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/browser/window' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/classify_rings' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/color_ramp' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/config' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/dictionary_coder' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/dispatcher' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/dom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/evented' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/find_pole_of_inaccessibility' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/global_worker_pool' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/image' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/intersection_tests' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/is_char_in_unicode_block' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/mapbox' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/performance' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/script_detection' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/smart_wrap' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/struct_array' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/task_queue' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/throttle' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/tile_cover' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/token' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/util' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/vectortile_to_geojson' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/verticalize_punctuation' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/web_worker_transfer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/web_worker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/window' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/worker_pool' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapbox-gl/build/generate-access-token-script.js' {
  declare module.exports: $Exports<'mapbox-gl/build/generate-access-token-script'>;
}
declare module 'mapbox-gl/build/generate-flow-typed-style-spec.js' {
  declare module.exports: $Exports<'mapbox-gl/build/generate-flow-typed-style-spec'>;
}
declare module 'mapbox-gl/build/generate-struct-arrays.js' {
  declare module.exports: $Exports<'mapbox-gl/build/generate-struct-arrays'>;
}
declare module 'mapbox-gl/build/generate-style-code.js' {
  declare module.exports: $Exports<'mapbox-gl/build/generate-style-code'>;
}
declare module 'mapbox-gl/build/minifyify_style_spec.js' {
  declare module.exports: $Exports<'mapbox-gl/build/minifyify_style_spec'>;
}
declare module 'mapbox-gl/build/rollup_plugin_minify_style_spec.js' {
  declare module.exports: $Exports<'mapbox-gl/build/rollup_plugin_minify_style_spec'>;
}
declare module 'mapbox-gl/build/rollup_plugins.js' {
  declare module.exports: $Exports<'mapbox-gl/build/rollup_plugins'>;
}
declare module 'mapbox-gl/build/strictify.js' {
  declare module.exports: $Exports<'mapbox-gl/build/strictify'>;
}
declare module 'mapbox-gl/dist/mapbox-gl-dev.js' {
  declare module.exports: $Exports<'mapbox-gl/dist/mapbox-gl-dev'>;
}
declare module 'mapbox-gl/dist/mapbox-gl.js' {
  declare module.exports: $Exports<'mapbox-gl/dist/mapbox-gl'>;
}
declare module 'mapbox-gl/dist/style-spec/index.js' {
  declare module.exports: $Exports<'mapbox-gl/dist/style-spec/index'>;
}
declare module 'mapbox-gl/flow-typed/geojson.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/geojson'>;
}
declare module 'mapbox-gl/flow-typed/mapbox-gl-js-test.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/mapbox-gl-js-test'>;
}
declare module 'mapbox-gl/flow-typed/mapbox-gl-supported.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/mapbox-gl-supported'>;
}
declare module 'mapbox-gl/flow-typed/mapbox-unitbezier.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/mapbox-unitbezier'>;
}
declare module 'mapbox-gl/flow-typed/pbf.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/pbf'>;
}
declare module 'mapbox-gl/flow-typed/point-geometry.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/point-geometry'>;
}
declare module 'mapbox-gl/flow-typed/pointlike.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/pointlike'>;
}
declare module 'mapbox-gl/flow-typed/shelf-pack.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/shelf-pack'>;
}
declare module 'mapbox-gl/flow-typed/style-spec.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/style-spec'>;
}
declare module 'mapbox-gl/flow-typed/unitbezier.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/unitbezier'>;
}
declare module 'mapbox-gl/flow-typed/vector-tile.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/vector-tile'>;
}
declare module 'mapbox-gl/flow-typed/window.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-typed/window'>;
}
declare module 'mapbox-gl/src/data/array_types.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/array_types'>;
}
declare module 'mapbox-gl/src/data/bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/circle_attributes.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/circle_attributes'>;
}
declare module 'mapbox-gl/src/data/bucket/circle_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/circle_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/fill_attributes.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/fill_attributes'>;
}
declare module 'mapbox-gl/src/data/bucket/fill_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/fill_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/fill_extrusion_attributes.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/fill_extrusion_attributes'>;
}
declare module 'mapbox-gl/src/data/bucket/fill_extrusion_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/fill_extrusion_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/heatmap_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/heatmap_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/line_attributes.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/line_attributes'>;
}
declare module 'mapbox-gl/src/data/bucket/line_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/line_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/symbol_attributes.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/symbol_attributes'>;
}
declare module 'mapbox-gl/src/data/bucket/symbol_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/symbol_bucket'>;
}
declare module 'mapbox-gl/src/data/dem_data.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/dem_data'>;
}
declare module 'mapbox-gl/src/data/extent.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/extent'>;
}
declare module 'mapbox-gl/src/data/feature_index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/feature_index'>;
}
declare module 'mapbox-gl/src/data/index_array_type.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/index_array_type'>;
}
declare module 'mapbox-gl/src/data/load_geometry.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/load_geometry'>;
}
declare module 'mapbox-gl/src/data/pos_attributes.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/pos_attributes'>;
}
declare module 'mapbox-gl/src/data/program_configuration.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/program_configuration'>;
}
declare module 'mapbox-gl/src/data/raster_bounds_attributes.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/raster_bounds_attributes'>;
}
declare module 'mapbox-gl/src/data/segment.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/segment'>;
}
declare module 'mapbox-gl/src/geo/coordinate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/coordinate'>;
}
declare module 'mapbox-gl/src/geo/lng_lat_bounds.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/lng_lat_bounds'>;
}
declare module 'mapbox-gl/src/geo/lng_lat.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/lng_lat'>;
}
declare module 'mapbox-gl/src/geo/transform.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/transform'>;
}
declare module 'mapbox-gl/src/gl/color_mode.js' {
  declare module.exports: $Exports<'mapbox-gl/src/gl/color_mode'>;
}
declare module 'mapbox-gl/src/gl/context.js' {
  declare module.exports: $Exports<'mapbox-gl/src/gl/context'>;
}
declare module 'mapbox-gl/src/gl/depth_mode.js' {
  declare module.exports: $Exports<'mapbox-gl/src/gl/depth_mode'>;
}
declare module 'mapbox-gl/src/gl/framebuffer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/gl/framebuffer'>;
}
declare module 'mapbox-gl/src/gl/index_buffer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/gl/index_buffer'>;
}
declare module 'mapbox-gl/src/gl/stencil_mode.js' {
  declare module.exports: $Exports<'mapbox-gl/src/gl/stencil_mode'>;
}
declare module 'mapbox-gl/src/gl/types.js' {
  declare module.exports: $Exports<'mapbox-gl/src/gl/types'>;
}
declare module 'mapbox-gl/src/gl/value.js' {
  declare module.exports: $Exports<'mapbox-gl/src/gl/value'>;
}
declare module 'mapbox-gl/src/gl/vertex_buffer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/gl/vertex_buffer'>;
}
declare module 'mapbox-gl/src/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/index'>;
}
declare module 'mapbox-gl/src/render/draw_background.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_background'>;
}
declare module 'mapbox-gl/src/render/draw_circle.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_circle'>;
}
declare module 'mapbox-gl/src/render/draw_collision_debug.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_collision_debug'>;
}
declare module 'mapbox-gl/src/render/draw_debug.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_debug'>;
}
declare module 'mapbox-gl/src/render/draw_fill_extrusion.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_fill_extrusion'>;
}
declare module 'mapbox-gl/src/render/draw_fill.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_fill'>;
}
declare module 'mapbox-gl/src/render/draw_heatmap.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_heatmap'>;
}
declare module 'mapbox-gl/src/render/draw_hillshade.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_hillshade'>;
}
declare module 'mapbox-gl/src/render/draw_line.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_line'>;
}
declare module 'mapbox-gl/src/render/draw_raster.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_raster'>;
}
declare module 'mapbox-gl/src/render/draw_symbol.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_symbol'>;
}
declare module 'mapbox-gl/src/render/glyph_atlas.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/glyph_atlas'>;
}
declare module 'mapbox-gl/src/render/glyph_manager.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/glyph_manager'>;
}
declare module 'mapbox-gl/src/render/image_atlas.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/image_atlas'>;
}
declare module 'mapbox-gl/src/render/image_manager.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/image_manager'>;
}
declare module 'mapbox-gl/src/render/line_atlas.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/line_atlas'>;
}
declare module 'mapbox-gl/src/render/painter.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/painter'>;
}
declare module 'mapbox-gl/src/render/pattern.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/pattern'>;
}
declare module 'mapbox-gl/src/render/program.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/program'>;
}
declare module 'mapbox-gl/src/render/texture.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/texture'>;
}
declare module 'mapbox-gl/src/render/tile_mask.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/tile_mask'>;
}
declare module 'mapbox-gl/src/render/vertex_array_object.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/vertex_array_object'>;
}
declare module 'mapbox-gl/src/shaders/encode_attribute.js' {
  declare module.exports: $Exports<'mapbox-gl/src/shaders/encode_attribute'>;
}
declare module 'mapbox-gl/src/shaders/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/shaders/index'>;
}
declare module 'mapbox-gl/src/source/canvas_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/canvas_source'>;
}
declare module 'mapbox-gl/src/source/geojson_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/geojson_source'>;
}
declare module 'mapbox-gl/src/source/geojson_worker_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/geojson_worker_source'>;
}
declare module 'mapbox-gl/src/source/geojson_wrapper.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/geojson_wrapper'>;
}
declare module 'mapbox-gl/src/source/image_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/image_source'>;
}
declare module 'mapbox-gl/src/source/load_tilejson.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/load_tilejson'>;
}
declare module 'mapbox-gl/src/source/pixels_to_tile_units.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/pixels_to_tile_units'>;
}
declare module 'mapbox-gl/src/source/query_features.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/query_features'>;
}
declare module 'mapbox-gl/src/source/raster_dem_tile_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/raster_dem_tile_source'>;
}
declare module 'mapbox-gl/src/source/raster_dem_tile_worker_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/raster_dem_tile_worker_source'>;
}
declare module 'mapbox-gl/src/source/raster_tile_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/raster_tile_source'>;
}
declare module 'mapbox-gl/src/source/rtl_text_plugin.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/rtl_text_plugin'>;
}
declare module 'mapbox-gl/src/source/source_cache.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/source_cache'>;
}
declare module 'mapbox-gl/src/source/source_state.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/source_state'>;
}
declare module 'mapbox-gl/src/source/source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/source'>;
}
declare module 'mapbox-gl/src/source/tile_bounds.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/tile_bounds'>;
}
declare module 'mapbox-gl/src/source/tile_cache.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/tile_cache'>;
}
declare module 'mapbox-gl/src/source/tile_id.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/tile_id'>;
}
declare module 'mapbox-gl/src/source/tile.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/tile'>;
}
declare module 'mapbox-gl/src/source/vector_tile_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/vector_tile_source'>;
}
declare module 'mapbox-gl/src/source/vector_tile_worker_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/vector_tile_worker_source'>;
}
declare module 'mapbox-gl/src/source/video_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/video_source'>;
}
declare module 'mapbox-gl/src/source/worker_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/worker_source'>;
}
declare module 'mapbox-gl/src/source/worker_tile.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/worker_tile'>;
}
declare module 'mapbox-gl/src/source/worker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/worker'>;
}
declare module 'mapbox-gl/src/style-spec/build/strictify.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/build/strictify'>;
}
declare module 'mapbox-gl/src/style-spec/composite.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/composite'>;
}
declare module 'mapbox-gl/src/style-spec/declass.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/declass'>;
}
declare module 'mapbox-gl/src/style-spec/deref.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/deref'>;
}
declare module 'mapbox-gl/src/style-spec/diff.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/diff'>;
}
declare module 'mapbox-gl/src/style-spec/dist/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/dist/index'>;
}
declare module 'mapbox-gl/src/style-spec/error/parsing_error.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/error/parsing_error'>;
}
declare module 'mapbox-gl/src/style-spec/error/validation_error.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/error/validation_error'>;
}
declare module 'mapbox-gl/src/style-spec/expression/compound_expression.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/compound_expression'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/array.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/array'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/assertion.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/assertion'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/at.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/at'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/case.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/case'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/coalesce.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/coalesce'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/coercion.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/coercion'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/collator.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/collator'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/equals.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/equals'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/index'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/interpolate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/interpolate'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/length.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/length'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/let.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/let'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/literal.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/literal'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/match.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/match'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/step.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/step'>;
}
declare module 'mapbox-gl/src/style-spec/expression/definitions/var.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/definitions/var'>;
}
declare module 'mapbox-gl/src/style-spec/expression/evaluation_context.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/evaluation_context'>;
}
declare module 'mapbox-gl/src/style-spec/expression/expression.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/expression'>;
}
declare module 'mapbox-gl/src/style-spec/expression/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/index'>;
}
declare module 'mapbox-gl/src/style-spec/expression/is_constant.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/is_constant'>;
}
declare module 'mapbox-gl/src/style-spec/expression/parsing_context.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/parsing_context'>;
}
declare module 'mapbox-gl/src/style-spec/expression/parsing_error.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/parsing_error'>;
}
declare module 'mapbox-gl/src/style-spec/expression/runtime_error.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/runtime_error'>;
}
declare module 'mapbox-gl/src/style-spec/expression/scope.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/scope'>;
}
declare module 'mapbox-gl/src/style-spec/expression/stops.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/stops'>;
}
declare module 'mapbox-gl/src/style-spec/expression/types.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/types'>;
}
declare module 'mapbox-gl/src/style-spec/expression/values.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/expression/values'>;
}
declare module 'mapbox-gl/src/style-spec/feature_filter/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/feature_filter/index'>;
}
declare module 'mapbox-gl/src/style-spec/format.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/format'>;
}
declare module 'mapbox-gl/src/style-spec/function/convert.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/function/convert'>;
}
declare module 'mapbox-gl/src/style-spec/function/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/function/index'>;
}
declare module 'mapbox-gl/src/style-spec/group_by_layout.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/group_by_layout'>;
}
declare module 'mapbox-gl/src/style-spec/migrate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/migrate'>;
}
declare module 'mapbox-gl/src/style-spec/migrate/v8.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/migrate/v8'>;
}
declare module 'mapbox-gl/src/style-spec/migrate/v9.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/migrate/v9'>;
}
declare module 'mapbox-gl/src/style-spec/reference/latest.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/reference/latest'>;
}
declare module 'mapbox-gl/src/style-spec/rollup.config.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/rollup.config'>;
}
declare module 'mapbox-gl/src/style-spec/style-spec.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/style-spec'>;
}
declare module 'mapbox-gl/src/style-spec/util/color_spaces.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/color_spaces'>;
}
declare module 'mapbox-gl/src/style-spec/util/color.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/color'>;
}
declare module 'mapbox-gl/src/style-spec/util/deep_equal.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/deep_equal'>;
}
declare module 'mapbox-gl/src/style-spec/util/eval_support.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/eval_support'>;
}
declare module 'mapbox-gl/src/style-spec/util/extend.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/extend'>;
}
declare module 'mapbox-gl/src/style-spec/util/get_type.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/get_type'>;
}
declare module 'mapbox-gl/src/style-spec/util/interpolate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/interpolate'>;
}
declare module 'mapbox-gl/src/style-spec/util/properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/properties'>;
}
declare module 'mapbox-gl/src/style-spec/util/ref_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/ref_properties'>;
}
declare module 'mapbox-gl/src/style-spec/util/result.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/result'>;
}
declare module 'mapbox-gl/src/style-spec/util/unbundle_jsonlint.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/unbundle_jsonlint'>;
}
declare module 'mapbox-gl/src/style-spec/validate_style.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate_style'>;
}
declare module 'mapbox-gl/src/style-spec/validate_style.min.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate_style.min'>;
}
declare module 'mapbox-gl/src/style-spec/validate/latest.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/latest'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_array.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_array'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_boolean.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_boolean'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_color.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_color'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_constants.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_constants'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_enum.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_enum'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_expression.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_expression'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_filter.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_filter'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_function.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_function'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_glyphs_url.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_glyphs_url'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_layer'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_layout_property.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_layout_property'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_light.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_light'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_number.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_number'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_object.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_object'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_paint_property.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_paint_property'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_property.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_property'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_source'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_string.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_string'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate'>;
}
declare module 'mapbox-gl/src/style/create_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/create_style_layer'>;
}
declare module 'mapbox-gl/src/style/cross_faded.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/cross_faded'>;
}
declare module 'mapbox-gl/src/style/evaluation_parameters.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/evaluation_parameters'>;
}
declare module 'mapbox-gl/src/style/light.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/light'>;
}
declare module 'mapbox-gl/src/style/load_glyph_range.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/load_glyph_range'>;
}
declare module 'mapbox-gl/src/style/load_sprite.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/load_sprite'>;
}
declare module 'mapbox-gl/src/style/parse_glyph_pbf.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/parse_glyph_pbf'>;
}
declare module 'mapbox-gl/src/style/pauseable_placement.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/pauseable_placement'>;
}
declare module 'mapbox-gl/src/style/properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/properties'>;
}
declare module 'mapbox-gl/src/style/query_utils.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/query_utils'>;
}
declare module 'mapbox-gl/src/style/style_glyph.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_glyph'>;
}
declare module 'mapbox-gl/src/style/style_image.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_image'>;
}
declare module 'mapbox-gl/src/style/style_layer_index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer_index'>;
}
declare module 'mapbox-gl/src/style/style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/background_style_layer_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/background_style_layer_properties'>;
}
declare module 'mapbox-gl/src/style/style_layer/background_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/background_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/circle_style_layer_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/circle_style_layer_properties'>;
}
declare module 'mapbox-gl/src/style/style_layer/circle_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/circle_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer_properties'>;
}
declare module 'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/fill_style_layer_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/fill_style_layer_properties'>;
}
declare module 'mapbox-gl/src/style/style_layer/fill_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/fill_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/heatmap_style_layer_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/heatmap_style_layer_properties'>;
}
declare module 'mapbox-gl/src/style/style_layer/heatmap_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/heatmap_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/hillshade_style_layer_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/hillshade_style_layer_properties'>;
}
declare module 'mapbox-gl/src/style/style_layer/hillshade_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/hillshade_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/line_style_layer_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/line_style_layer_properties'>;
}
declare module 'mapbox-gl/src/style/style_layer/line_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/line_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/raster_style_layer_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/raster_style_layer_properties'>;
}
declare module 'mapbox-gl/src/style/style_layer/raster_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/raster_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/symbol_style_layer_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/symbol_style_layer_properties'>;
}
declare module 'mapbox-gl/src/style/style_layer/symbol_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/symbol_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/typed_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/typed_style_layer'>;
}
declare module 'mapbox-gl/src/style/style.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style'>;
}
declare module 'mapbox-gl/src/style/validate_style.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/validate_style'>;
}
declare module 'mapbox-gl/src/style/zoom_history.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/zoom_history'>;
}
declare module 'mapbox-gl/src/symbol/anchor.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/anchor'>;
}
declare module 'mapbox-gl/src/symbol/check_max_angle.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/check_max_angle'>;
}
declare module 'mapbox-gl/src/symbol/clip_line.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/clip_line'>;
}
declare module 'mapbox-gl/src/symbol/collision_feature.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/collision_feature'>;
}
declare module 'mapbox-gl/src/symbol/collision_index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/collision_index'>;
}
declare module 'mapbox-gl/src/symbol/cross_tile_symbol_index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/cross_tile_symbol_index'>;
}
declare module 'mapbox-gl/src/symbol/get_anchors.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/get_anchors'>;
}
declare module 'mapbox-gl/src/symbol/grid_index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/grid_index'>;
}
declare module 'mapbox-gl/src/symbol/mergelines.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/mergelines'>;
}
declare module 'mapbox-gl/src/symbol/opacity_state.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/opacity_state'>;
}
declare module 'mapbox-gl/src/symbol/placement.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/placement'>;
}
declare module 'mapbox-gl/src/symbol/projection.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/projection'>;
}
declare module 'mapbox-gl/src/symbol/quads.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/quads'>;
}
declare module 'mapbox-gl/src/symbol/shaping.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/shaping'>;
}
declare module 'mapbox-gl/src/symbol/symbol_layout.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/symbol_layout'>;
}
declare module 'mapbox-gl/src/symbol/symbol_size.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/symbol_size'>;
}
declare module 'mapbox-gl/src/symbol/transform_text.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/transform_text'>;
}
declare module 'mapbox-gl/src/types/callback.js' {
  declare module.exports: $Exports<'mapbox-gl/src/types/callback'>;
}
declare module 'mapbox-gl/src/types/cancelable.js' {
  declare module.exports: $Exports<'mapbox-gl/src/types/cancelable'>;
}
declare module 'mapbox-gl/src/types/performance_resource_timing.js' {
  declare module.exports: $Exports<'mapbox-gl/src/types/performance_resource_timing'>;
}
declare module 'mapbox-gl/src/types/tilejson.js' {
  declare module.exports: $Exports<'mapbox-gl/src/types/tilejson'>;
}
declare module 'mapbox-gl/src/types/transferable.js' {
  declare module.exports: $Exports<'mapbox-gl/src/types/transferable'>;
}
declare module 'mapbox-gl/src/ui/anchor.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/anchor'>;
}
declare module 'mapbox-gl/src/ui/bind_handlers.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/bind_handlers'>;
}
declare module 'mapbox-gl/src/ui/camera.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/camera'>;
}
declare module 'mapbox-gl/src/ui/control/attribution_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/attribution_control'>;
}
declare module 'mapbox-gl/src/ui/control/fullscreen_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/fullscreen_control'>;
}
declare module 'mapbox-gl/src/ui/control/geolocate_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/geolocate_control'>;
}
declare module 'mapbox-gl/src/ui/control/logo_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/logo_control'>;
}
declare module 'mapbox-gl/src/ui/control/navigation_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/navigation_control'>;
}
declare module 'mapbox-gl/src/ui/control/scale_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/scale_control'>;
}
declare module 'mapbox-gl/src/ui/events.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/events'>;
}
declare module 'mapbox-gl/src/ui/handler/box_zoom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/box_zoom'>;
}
declare module 'mapbox-gl/src/ui/handler/dblclick_zoom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/dblclick_zoom'>;
}
declare module 'mapbox-gl/src/ui/handler/drag_pan.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/drag_pan'>;
}
declare module 'mapbox-gl/src/ui/handler/drag_rotate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/drag_rotate'>;
}
declare module 'mapbox-gl/src/ui/handler/keyboard.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/keyboard'>;
}
declare module 'mapbox-gl/src/ui/handler/scroll_zoom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/scroll_zoom'>;
}
declare module 'mapbox-gl/src/ui/handler/touch_zoom_rotate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/touch_zoom_rotate'>;
}
declare module 'mapbox-gl/src/ui/hash.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/hash'>;
}
declare module 'mapbox-gl/src/ui/map.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/map'>;
}
declare module 'mapbox-gl/src/ui/marker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/marker'>;
}
declare module 'mapbox-gl/src/ui/popup.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/popup'>;
}
declare module 'mapbox-gl/src/util/actor.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/actor'>;
}
declare module 'mapbox-gl/src/util/ajax.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/ajax'>;
}
declare module 'mapbox-gl/src/util/browser.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/browser'>;
}
declare module 'mapbox-gl/src/util/browser/web_worker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/browser/web_worker'>;
}
declare module 'mapbox-gl/src/util/browser/window.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/browser/window'>;
}
declare module 'mapbox-gl/src/util/classify_rings.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/classify_rings'>;
}
declare module 'mapbox-gl/src/util/color_ramp.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/color_ramp'>;
}
declare module 'mapbox-gl/src/util/config.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/config'>;
}
declare module 'mapbox-gl/src/util/dictionary_coder.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/dictionary_coder'>;
}
declare module 'mapbox-gl/src/util/dispatcher.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/dispatcher'>;
}
declare module 'mapbox-gl/src/util/dom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/dom'>;
}
declare module 'mapbox-gl/src/util/evented.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/evented'>;
}
declare module 'mapbox-gl/src/util/find_pole_of_inaccessibility.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/find_pole_of_inaccessibility'>;
}
declare module 'mapbox-gl/src/util/global_worker_pool.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/global_worker_pool'>;
}
declare module 'mapbox-gl/src/util/image.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/image'>;
}
declare module 'mapbox-gl/src/util/intersection_tests.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/intersection_tests'>;
}
declare module 'mapbox-gl/src/util/is_char_in_unicode_block.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/is_char_in_unicode_block'>;
}
declare module 'mapbox-gl/src/util/mapbox.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/mapbox'>;
}
declare module 'mapbox-gl/src/util/performance.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/performance'>;
}
declare module 'mapbox-gl/src/util/script_detection.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/script_detection'>;
}
declare module 'mapbox-gl/src/util/smart_wrap.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/smart_wrap'>;
}
declare module 'mapbox-gl/src/util/struct_array.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/struct_array'>;
}
declare module 'mapbox-gl/src/util/task_queue.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/task_queue'>;
}
declare module 'mapbox-gl/src/util/throttle.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/throttle'>;
}
declare module 'mapbox-gl/src/util/tile_cover.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/tile_cover'>;
}
declare module 'mapbox-gl/src/util/token.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/token'>;
}
declare module 'mapbox-gl/src/util/util.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/util'>;
}
declare module 'mapbox-gl/src/util/vectortile_to_geojson.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/vectortile_to_geojson'>;
}
declare module 'mapbox-gl/src/util/verticalize_punctuation.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/verticalize_punctuation'>;
}
declare module 'mapbox-gl/src/util/web_worker_transfer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/web_worker_transfer'>;
}
declare module 'mapbox-gl/src/util/web_worker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/web_worker'>;
}
declare module 'mapbox-gl/src/util/window.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/window'>;
}
declare module 'mapbox-gl/src/util/worker_pool.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/worker_pool'>;
}
