// flow-typed signature: 7d9346e84ee4ffa19367a05b4d2b3367
// flow-typed version: <<STUB>>/mem_v^3.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mem' {
  declare module.exports: declare module.exports: <T: () => mixed>(func: T, options: Object) => T;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mem/index' {
  declare module.exports: $Exports<'mem'>;
}
declare module 'mem/index.js' {
  declare module.exports: $Exports<'mem'>;
}
