// flow-typed signature: 1a8a4e0645e61fa3c8480d59d8090761
// flow-typed version: <<STUB>>/precinct_v^6.1.2/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'precinct'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'precinct' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'precinct/bin/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'precinct/bin/cli.js' {
  declare module.exports: $Exports<'precinct/bin/cli'>;
}
declare module 'precinct/index' {
  declare module.exports: $Exports<'precinct'>;
}
declare module 'precinct/index.js' {
  declare module.exports: $Exports<'precinct'>;
}
