// flow-typed signature: dc71ce222b3cf61aa64d1c3ff91f7eac
// flow-typed version: <<STUB>>/quick-lru_v^4.0.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'quick-lru'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'quick-lru' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'quick-lru/index' {
  declare module.exports: $Exports<'quick-lru'>;
}
declare module 'quick-lru/index.js' {
  declare module.exports: $Exports<'quick-lru'>;
}
