// flow-typed signature: 52b2c90c29177060e2aa1defd00d32d4
// flow-typed version: <<STUB>>/re-carousel_v^2.3.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   're-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 're-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 're-carousel/dist/carousel' {
  declare module.exports: any;
}

// Filename aliases
declare module 're-carousel/dist/carousel.js' {
  declare module.exports: $Exports<'re-carousel/dist/carousel'>;
}
