// flow-typed signature: f16422c50cc5293bdd53234ca590abe1
// flow-typed version: <<STUB>>/round-to_v^4.0.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'round-to'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'round-to' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'round-to/index' {
  declare module.exports: $Exports<'round-to'>;
}
declare module 'round-to/index.js' {
  declare module.exports: $Exports<'round-to'>;
}
