// flow-typed signature: a5fbc5a63662059008d1d11c00ea246d
// flow-typed version: <<STUB>>/sexagesimal_v^0.5.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sexagesimal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sexagesimal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sexagesimal/sexagesimal' {
  declare module.exports: any;
}

declare module 'sexagesimal/test/format' {
  declare module.exports: any;
}

declare module 'sexagesimal/test/formatpair' {
  declare module.exports: any;
}

declare module 'sexagesimal/test/invalid' {
  declare module.exports: any;
}

declare module 'sexagesimal/test/pair' {
  declare module.exports: any;
}

declare module 'sexagesimal/test/parse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sexagesimal/index' {
  declare module.exports: $Exports<'sexagesimal'>;
}
declare module 'sexagesimal/index.js' {
  declare module.exports: $Exports<'sexagesimal'>;
}
declare module 'sexagesimal/sexagesimal.js' {
  declare module.exports: $Exports<'sexagesimal/sexagesimal'>;
}
declare module 'sexagesimal/test/format.js' {
  declare module.exports: $Exports<'sexagesimal/test/format'>;
}
declare module 'sexagesimal/test/formatpair.js' {
  declare module.exports: $Exports<'sexagesimal/test/formatpair'>;
}
declare module 'sexagesimal/test/invalid.js' {
  declare module.exports: $Exports<'sexagesimal/test/invalid'>;
}
declare module 'sexagesimal/test/pair.js' {
  declare module.exports: $Exports<'sexagesimal/test/pair'>;
}
declare module 'sexagesimal/test/parse.js' {
  declare module.exports: $Exports<'sexagesimal/test/parse'>;
}
