// flow-typed signature: 58fd30dcc973c003e44e47b4132ec6bd
// flow-typed version: <<STUB>>/storybook-addon-docgen_v^4.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-docgen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-docgen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-docgen/dist/components/generateMarkdown' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/dist/constants' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/dist/DocPanel' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/dist/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/dist/register' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/example/Button' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/example/ButtonDocs' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/example/ButtonSimple' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/example/story' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/register' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/src/components/generateMarkdown' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/src/constants' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/src/DocPanel' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/src/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-docgen/src/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-docgen/dist/components/generateMarkdown.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/dist/components/generateMarkdown'>;
}
declare module 'storybook-addon-docgen/dist/constants.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/dist/constants'>;
}
declare module 'storybook-addon-docgen/dist/DocPanel.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/dist/DocPanel'>;
}
declare module 'storybook-addon-docgen/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/dist/index'>;
}
declare module 'storybook-addon-docgen/dist/register.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/dist/register'>;
}
declare module 'storybook-addon-docgen/example/Button.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/example/Button'>;
}
declare module 'storybook-addon-docgen/example/ButtonDocs.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/example/ButtonDocs'>;
}
declare module 'storybook-addon-docgen/example/ButtonSimple.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/example/ButtonSimple'>;
}
declare module 'storybook-addon-docgen/example/story.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/example/story'>;
}
declare module 'storybook-addon-docgen/register.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/register'>;
}
declare module 'storybook-addon-docgen/src/components/generateMarkdown.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/src/components/generateMarkdown'>;
}
declare module 'storybook-addon-docgen/src/constants.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/src/constants'>;
}
declare module 'storybook-addon-docgen/src/DocPanel.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/src/DocPanel'>;
}
declare module 'storybook-addon-docgen/src/index.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/src/index'>;
}
declare module 'storybook-addon-docgen/src/register.js' {
  declare module.exports: $Exports<'storybook-addon-docgen/src/register'>;
}
