// flow-typed signature: a54e162d7da24081320d2b74dd484c94
// flow-typed version: <<STUB>>/storybook-addon-react-docgen_v^1.2.2/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-react-docgen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-react-docgen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-react-docgen/dist/Components/makeTableComponent' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/PropTable' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/PropVal' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/Story' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/ArrayOf' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/Enum' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/InstanceOf' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/Literal' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/ObjectOf' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/OneOf' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/OneOfType' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/PrettyPropType' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/PropertyLabel' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/proptypes' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/Shape' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/Signature' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/Components/types/utils' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/dist/register' {
  declare module.exports: any;
}

declare module 'storybook-addon-react-docgen/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-react-docgen/dist/Components/makeTableComponent.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/makeTableComponent'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/PropTable.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/PropTable'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/PropVal.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/PropVal'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/Story.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/Story'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/ArrayOf.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/ArrayOf'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/Enum.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/Enum'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/InstanceOf.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/InstanceOf'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/Literal.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/Literal'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/ObjectOf.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/ObjectOf'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/OneOf.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/OneOf'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/OneOfType.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/OneOfType'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/PrettyPropType.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/PrettyPropType'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/PropertyLabel.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/PropertyLabel'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/proptypes.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/proptypes'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/Shape.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/Shape'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/Signature.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/Signature'>;
}
declare module 'storybook-addon-react-docgen/dist/Components/types/utils.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/Components/types/utils'>;
}
declare module 'storybook-addon-react-docgen/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/index'>;
}
declare module 'storybook-addon-react-docgen/dist/register.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/dist/register'>;
}
declare module 'storybook-addon-react-docgen/register.js' {
  declare module.exports: $Exports<'storybook-addon-react-docgen/register'>;
}
