// flow-typed signature: 31e8ab743db350bd86a8558e2437a395
// flow-typed version: <<STUB>>/tap_v^14.2.3/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tap/bin/jack' {
  declare module.exports: any;
}

declare module 'tap/bin/jsx' {
  declare module.exports: any;
}

declare module 'tap/bin/run' {
  declare module.exports: any;
}

declare module 'tap/lib/base' {
  declare module.exports: any;
}

declare module 'tap/lib/clean-yaml-object' {
  declare module.exports: any;
}

declare module 'tap/lib/diags' {
  declare module.exports: any;
}

declare module 'tap/lib/extra-from-error' {
  declare module.exports: any;
}

declare module 'tap/lib/mocha' {
  declare module.exports: any;
}

declare module 'tap/lib/obj-to-yaml' {
  declare module.exports: any;
}

declare module 'tap/lib/parse-test-args' {
  declare module.exports: any;
}

declare module 'tap/lib/point' {
  declare module.exports: any;
}

declare module 'tap/lib/repl' {
  declare module.exports: any;
}

declare module 'tap/lib/snapshot' {
  declare module.exports: any;
}

declare module 'tap/lib/spawn' {
  declare module.exports: any;
}

declare module 'tap/lib/stack' {
  declare module.exports: any;
}

declare module 'tap/lib/stdin' {
  declare module.exports: any;
}

declare module 'tap/lib/stdio-polyfill' {
  declare module.exports: any;
}

declare module 'tap/lib/synonyms' {
  declare module.exports: any;
}

declare module 'tap/lib/tap' {
  declare module.exports: any;
}

declare module 'tap/lib/test' {
  declare module.exports: any;
}

declare module 'tap/lib/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tap/bin/jack.js' {
  declare module.exports: $Exports<'tap/bin/jack'>;
}
declare module 'tap/bin/jsx.js' {
  declare module.exports: $Exports<'tap/bin/jsx'>;
}
declare module 'tap/bin/run.js' {
  declare module.exports: $Exports<'tap/bin/run'>;
}
declare module 'tap/lib/base.js' {
  declare module.exports: $Exports<'tap/lib/base'>;
}
declare module 'tap/lib/clean-yaml-object.js' {
  declare module.exports: $Exports<'tap/lib/clean-yaml-object'>;
}
declare module 'tap/lib/diags.js' {
  declare module.exports: $Exports<'tap/lib/diags'>;
}
declare module 'tap/lib/extra-from-error.js' {
  declare module.exports: $Exports<'tap/lib/extra-from-error'>;
}
declare module 'tap/lib/mocha.js' {
  declare module.exports: $Exports<'tap/lib/mocha'>;
}
declare module 'tap/lib/obj-to-yaml.js' {
  declare module.exports: $Exports<'tap/lib/obj-to-yaml'>;
}
declare module 'tap/lib/parse-test-args.js' {
  declare module.exports: $Exports<'tap/lib/parse-test-args'>;
}
declare module 'tap/lib/point.js' {
  declare module.exports: $Exports<'tap/lib/point'>;
}
declare module 'tap/lib/repl.js' {
  declare module.exports: $Exports<'tap/lib/repl'>;
}
declare module 'tap/lib/snapshot.js' {
  declare module.exports: $Exports<'tap/lib/snapshot'>;
}
declare module 'tap/lib/spawn.js' {
  declare module.exports: $Exports<'tap/lib/spawn'>;
}
declare module 'tap/lib/stack.js' {
  declare module.exports: $Exports<'tap/lib/stack'>;
}
declare module 'tap/lib/stdin.js' {
  declare module.exports: $Exports<'tap/lib/stdin'>;
}
declare module 'tap/lib/stdio-polyfill.js' {
  declare module.exports: $Exports<'tap/lib/stdio-polyfill'>;
}
declare module 'tap/lib/synonyms.js' {
  declare module.exports: $Exports<'tap/lib/synonyms'>;
}
declare module 'tap/lib/tap.js' {
  declare module.exports: $Exports<'tap/lib/tap'>;
}
declare module 'tap/lib/test.js' {
  declare module.exports: $Exports<'tap/lib/test'>;
}
declare module 'tap/lib/watch.js' {
  declare module.exports: $Exports<'tap/lib/watch'>;
}
