// flow-typed signature: 2002eff6887f43d5398cef4defe90693
// flow-typed version: <<STUB>>/url-regex_v^5.0.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'url-regex/index' {
  declare module.exports: $Exports<'url-regex'>;
}
declare module 'url-regex/index.js' {
  declare module.exports: $Exports<'url-regex'>;
}
