// flow-typed signature: 15c19b50a2d0c2290a38a5ed555771a1
// flow-typed version: <<STUB>>/@storybook/addon-actions_v^5.1.8/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-actions/dist/components/ActionLogger/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/components/ActionLogger/style' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/containers/ActionLogger/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/ActionDisplay' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/ActionOptions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/ActionsMap' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/DecoratorFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/HandlerFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/__tests__/action.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/__tests__/configureActions.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/action' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/actions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/configureActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/decorateAction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/withActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview/__tests__/action.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview/__tests__/configureActions.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-actions/dist/components/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/components/ActionLogger/index'>;
}
declare module '@storybook/addon-actions/dist/components/ActionLogger/style.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/components/ActionLogger/style'>;
}
declare module '@storybook/addon-actions/dist/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/constants'>;
}
declare module '@storybook/addon-actions/dist/containers/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/containers/ActionLogger/index'>;
}
declare module '@storybook/addon-actions/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/index'>;
}
declare module '@storybook/addon-actions/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/manager'>;
}
declare module '@storybook/addon-actions/dist/models/ActionDisplay.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/ActionDisplay'>;
}
declare module '@storybook/addon-actions/dist/models/ActionOptions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/ActionOptions'>;
}
declare module '@storybook/addon-actions/dist/models/ActionsMap.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/ActionsMap'>;
}
declare module '@storybook/addon-actions/dist/models/DecoratorFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/DecoratorFunction'>;
}
declare module '@storybook/addon-actions/dist/models/HandlerFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/HandlerFunction'>;
}
declare module '@storybook/addon-actions/dist/models/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/index'>;
}
declare module '@storybook/addon-actions/dist/preview/__tests__/action.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/__tests__/action.test'>;
}
declare module '@storybook/addon-actions/dist/preview/__tests__/configureActions.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/__tests__/configureActions.test'>;
}
declare module '@storybook/addon-actions/dist/preview/action.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/action'>;
}
declare module '@storybook/addon-actions/dist/preview/actions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/actions'>;
}
declare module '@storybook/addon-actions/dist/preview/configureActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/configureActions'>;
}
declare module '@storybook/addon-actions/dist/preview/decorateAction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/decorateAction'>;
}
declare module '@storybook/addon-actions/dist/preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/index'>;
}
declare module '@storybook/addon-actions/dist/preview/withActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/withActions'>;
}
declare module '@storybook/addon-actions/register.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/register'>;
}
declare module '@storybook/addon-actions/src/preview/__tests__/action.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview/__tests__/action.test'>;
}
declare module '@storybook/addon-actions/src/preview/__tests__/configureActions.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview/__tests__/configureActions.test'>;
}
